### ISSUE TITLE
请问程序集BinaryNumInputDialog无法引用，应该怎么办呢？

### ISSUE THREAD

**Issue by liangyanlin** [catmade/IEEE802.3-Frame#1]
请问程序集BinaryNumInputDialog无法引用，应该怎么办呢？

**Comment by catmade** [comment]
`BinaryNumInputDialog` 是我自己写的库，用来通过二进制的方式输入数字的，上传代码时忘了上传了，现在已经上传：[catmade/BinaryNumInputDialog](https://github.com/catmade/BinaryNumInputDialog)。

可以直接引入 `BinaryNumInputDialog` 项目中发布的 `BinaryNumInputDialog.dll` 文件来解决，或者自己手动下载 `BinaryNumInputDialog` 项目代码然后导入到该项目中。
